/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#include "Framewin_wallpaper_settingDLG.h"
#include "usart.h"
#include "bmpdisplay.h"
#include "fattester.h"	
#include "string.h"


// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0        (GUI_ID_USER + 0x00)
#define ID_DROPDOWN_0        (GUI_ID_USER + 0x01)
#define ID_BUTTON_0        (GUI_ID_USER + 0x02)
#define ID_BUTTON_1        (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HMEM Fwin_wallpaper_setting;
u8 wallpaper_path[50];
u8 sel_dropdown_wp_num = 0;
u8 sel_dropdown_wp_buf[30];	
//u8 wallpaper_list[][]


// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin_wallpaper_setting", ID_FRAMEWIN_0, 0, 20, 240, 270, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown_wp_file_path", ID_DROPDOWN_0, 6, 40, 200, 22, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_update", ID_BUTTON_0, 160, 80, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button_apply", ID_BUTTON_1, 70, 220, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	
	//u8 sel_dropdown_wp_num = 0;

	//u8 sel_dropdown_wp_buf[30];	
	
	//u8 wallpaper_path[50]="0:/wallpaper/";
	
	
	
	
	
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    //
    // Initialization of 'Framewin_wifiseting'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "Wallpaper");
    FRAMEWIN_SetTextColor(hItem, 0x00000000);
    FRAMEWIN_SetFont(hItem, GUI_FONT_16_1);
  
	FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
  
    //
    // Initialization of 'Dropdown_wp_file_path'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem, &GUI_Font20_1);
    DROPDOWN_SetListHeight(hItem, 100);
  
	mf_scan_files_wallpaper("0:/wallpaper",hItem);	
  
//	DROPDOWN_AddString(hItem,"0:/wallpaper/SQ_240X320.bmp");
//	DROPDOWN_AddString(hItem,"0:/wallpaper/SQ2_240X320.bmp");
//	DROPDOWN_AddString(hItem,"0:/wallpaper/SQ3_240X320.bmp");  
  
  
  
    //
    // Initialization of 'Button_update'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, "update");
    //
    // Initialization of 'Button_apply'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    BUTTON_SetText(hItem, "apply");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown_wp_file_path'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
	  
		sel_dropdown_wp_num = DROPDOWN_GetSel(pMsg->hWinSrc);
	  
		DROPDOWN_GetItemText(pMsg->hWinSrc,sel_dropdown_wp_num,sel_dropdown_wp_buf,50);
	  
		printf("%s\r\n",sel_dropdown_wp_buf);
	  
		//strcat(wallpaper_path,sel_dropdown_wp_buf);
		sprintf(wallpaper_path,"0:/wallpaper/%s",sel_dropdown_wp_buf);
	  
		printf("%s\r\n",wallpaper_path);
	  
		//删除存储设备
		GUI_MEMDEV_Delete(hBMP);	  
		//创建存储设备
		LoadBMP_UsingMEMDEV(wallpaper_path,0,0);
	  
	  
		
		

	  
	  
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button_update'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  
	  
		//mf_scan_files("0:/wallpaper");
	  
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
	    
		for(;0<DROPDOWN_GetNumItems(hItem);)
		{
			DROPDOWN_DeleteItem(hItem,0); 
		}

		mf_scan_files_wallpaper("0:/wallpaper",hItem);	
		
	  
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button_apply'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_DELETE:
	  break;	
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin_wallpaper_setting
*/

WM_HWIN CreateFramewin_wallpaper_setting(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  //设置模态窗口
  WM_MakeModal(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
