/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Window_StatusBarDLG.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0      (GUI_ID_USER + 0x00)
#define ID_TEXT_0      (GUI_ID_USER + 0xC1)
#define ID_ICONVIEW_WIFI      (GUI_ID_USER + 0xC2)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmwifi42_20;

extern GUI_CONST_STORAGE GUI_BITMAP bmwifi42_20_off;



// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window_StatusBar", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 48, 16, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_WIFI, 185, 0, 50, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "00:00");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_TOP);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_WIFI: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow_StatusBar
*/

WM_HWIN CreateWindow_StatusBar(void) {
  WM_HWIN hWin,hWin_TEXT;

//  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

    hWin = ICONVIEW_CreateEx(
                             220,0,
                             20,20,
                             WM_HBKWIN,
                             WM_CF_SHOW|WM_CF_STAYONTOP|WM_CF_HASTRANS,
                             0,
                             ID_ICONVIEW_WIFI,
                             20,20
                             );

    ICONVIEW_SetIconAlign(hWin,ICONVIEW_IA_HCENTER|ICONVIEW_IA_VCENTER);
    ICONVIEW_SetFrame(hWin,GUI_COORD_X,0);
    ICONVIEW_SetFrame(hWin,GUI_COORD_Y,0);
    ICONVIEW_SetSpace(hWin,GUI_COORD_X,0);
    ICONVIEW_SetSpace(hWin,GUI_COORD_Y,0);
    ICONVIEW_SetBkColor(hWin,ICONVIEW_CI_SEL,GUI_WHITE|0xFF000000);//´ý¶¨
    ICONVIEW_AddBitmapItem(hWin,&bmwifi42_20_off,"");

    hWin_TEXT = TEXT_CreateEx(0,0,
                              72,20,
                              WM_HBKWIN,
                              WM_CF_SHOW|WM_CF_STAYONTOP|WM_CF_HASTRANS,
                              0,
                              ID_TEXT_0,
                              ""
                              );

    TEXT_SetTextColor(hWin_TEXT,GUI_WHITE);
    TEXT_SetTextAlign(hWin_TEXT, GUI_TA_LEFT );
    TEXT_SetFont(hWin_TEXT, GUI_FONT_20_1);
    TEXT_SetText(hWin_TEXT, "00:00");



  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
