/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Window_iconDLG.h"
#include "bmpdisplay.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_ICONVIEW_0        (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmcalculator2_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmcalendar_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmgallery_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmmaps_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmmms_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmsupermarket_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmtorchactivity_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmweather_48;

extern GUI_CONST_STORAGE GUI_BITMAP bmapic25494_240X320;

extern GUI_CONST_STORAGE GUI_BITMAP bmarrowhead_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmfour17_48;
extern GUI_CONST_STORAGE GUI_BITMAP bmoutline5_24;

extern GUI_CONST_STORAGE GUI_BITMAP bmarrowhead2_48;

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_48_3;

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_48_565_b;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window_icon", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_0, 0, 50, 240, 320, WM_CF_SHOW | WM_CF_HASTRANS, 0x00400040, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog_icon(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN hItem;
  // USER END

  switch (pMsg->MsgId) {
	  
    case WM_PAINT:
      //GUI_DrawBitmap(&bmapic25494_240X320,0,0);
		bmpdisplay_demo();
    break;	  
	  
	  
	  
/*
  case WM_INIT_DIALOG:




    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_0);

    ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_HCENTER|ICONVIEW_IA_VCENTER);

    ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_UNSEL, GUI_BLUE);

    ICONVIEW_SetTextColor(hItem, ICONVIEW_CI_SEL, GUI_GREEN);

    ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_SEL, GUI_WHITE | 0xC0000000);

    ICONVIEW_SetFrame(hItem, GUI_COORD_X, (240-64*3)/2); //设置图标到IconView边框的间距

    ICONVIEW_SetFrame(hItem, GUI_COORD_Y, 0);

    ICONVIEW_SetSpace(hItem, GUI_COORD_X, 0);//设置图标和图标之间的间距

    ICONVIEW_SetSpace(hItem, GUI_COORD_Y, 0);

    ICONVIEW_SetFont(hItem, GUI_FONT_10_1);

    ICONVIEW_AddBitmapItem(hItem, &bmcalculator2_48, "calcu");//添加图标项

    ICONVIEW_AddBitmapItem(hItem, &bmcalendar_48, "calen");

    ICONVIEW_AddBitmapItem(hItem, &bmgallery_48, "gallr");

    ICONVIEW_AddBitmapItem(hItem, &bmmaps_48, "maps");

    ICONVIEW_AddBitmapItem(hItem, &bmmms_48, "mms");

    ICONVIEW_AddBitmapItem(hItem, &bmsettings_48, "set");

    ICONVIEW_AddBitmapItem(hItem, &bmsupermarket_48, "super");

    ICONVIEW_AddBitmapItem(hItem, &bmtorchactivity_48, "torcha");

    ICONVIEW_AddBitmapItem(hItem, &bmweather_48, "weather");



    ICONVIEW_AddBitmapItem(hItem, &bmfour17_48,"");

    ICONVIEW_AddBitmapItem(hItem, &bmoutline5_24,"");

    ICONVIEW_AddBitmapItem(hItem, &bmarrowhead2_48,"");

      break;
     */

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        switch(ICONVIEW_GetSel(pMsg->hWinSrc))
        {
        case 0:
            //CreateWindow_home();
            break;
        default:
            break;
        }
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow_icon
*/

WM_HWIN CreateWindow_icon(void) {
  WM_HWIN hWin;

  //hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	
//	WM_SetCallback(WM_HBKWIN,_cbDialog_icon);	
	
  hWin = ICONVIEW_CreateEx(24,50,
                           192,192,
                           WM_HBKWIN,
                           WM_CF_SHOW|WM_CF_HASTRANS,
                           0,
                           ID_ICONVIEW_0,
                           64,64
                           );


    ICONVIEW_SetIconAlign(hWin, ICONVIEW_IA_HCENTER|ICONVIEW_IA_VCENTER);

    ICONVIEW_SetTextColor(hWin, ICONVIEW_CI_UNSEL, GUI_BLUE);

    ICONVIEW_SetTextColor(hWin, ICONVIEW_CI_SEL, GUI_GREEN);

    ICONVIEW_SetBkColor(hWin, ICONVIEW_CI_SEL, GUI_WHITE | 0xC0000000);

     /* 设置图标被选中时的背景色 */
    //ICONVIEW_SetBkColor(hWin, ICONVIEW_CI_SEL, ((0x40uL << 24) | 0xFFFFFF));

    ICONVIEW_SetFrame(hWin, GUI_COORD_X, 0); //设置图标到IconView边框的间距

    ICONVIEW_SetFrame(hWin, GUI_COORD_Y, 0);

    ICONVIEW_SetSpace(hWin, GUI_COORD_X, 0);//设置图标和图标之间的间距

    ICONVIEW_SetSpace(hWin, GUI_COORD_Y, 0);

    ICONVIEW_SetFont(hWin, GUI_FONT_10_1);

    ICONVIEW_AddBitmapItem(hWin, &bmcalculator2_48, "calcu");//添加图标项

    ICONVIEW_AddBitmapItem(hWin, &bmcalendar_48, "calen");

    ICONVIEW_AddBitmapItem(hWin, &bmgallery_48, "gallr");

    ICONVIEW_AddBitmapItem(hWin, &bmmaps_48, "maps");

    ICONVIEW_AddBitmapItem(hWin, &bmmms_48, "mms");

    ICONVIEW_AddBitmapItem(hWin, &bmsettings_48, "set");

    ICONVIEW_AddBitmapItem(hWin, &bmsupermarket_48, "super");

    ICONVIEW_AddBitmapItem(hWin, &bmtorchactivity_48, "torcha");

    ICONVIEW_AddBitmapItem(hWin, &bmweather_48, "weather");

    /* 设置初始选择的图标，-1表示不选中任何图标 */
    ICONVIEW_SetSel(hWin, -1);

//    WM_SetCallback(WM_HBKWIN,_cbDialog_icon);

  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
