/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.26.                      *
*        Compiled Aug  8 2014, 14:49:30                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: settings_48_3                                         *
* Dimensions:  48 * 48                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmsettings_48_3;

static GUI_CONST_STORAGE unsigned char _acsettings_48_3[] = {
  /* RLE: 052 Pixels @ 000,000 */ 52, 0xFF, 
  /* ABS: 005 Pixels @ 004,001 */ 0, 5, 0xFD, 0xED, 0xAE, 0x6F, 0x4D, 
  /* RLE: 030 Pixels @ 009,001 */ 30, 0x46, 
  /* ABS: 004 Pixels @ 039,001 */ 0, 4, 0x4E, 0x71, 0xAD, 0xF4, 
  /* RLE: 008 Pixels @ 043,001 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 003,002 */ 0, 4, 0xFC, 0xB3, 0x3B, 0x08, 
  /* RLE: 034 Pixels @ 007,002 */ 34, 0x00, 
  /* ABS: 004 Pixels @ 041,002 */ 0, 4, 0x05, 0x32, 0xB9, 0xFD, 
  /* RLE: 005 Pixels @ 045,002 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 002,003 */ 0, 3, 0xFC, 0x89, 0x0D, 
  /* RLE: 038 Pixels @ 005,003 */ 38, 0x00, 
  /* ABS: 009 Pixels @ 043,003 */ 0, 9, 0x0C, 0x87, 0xFD, 0xFF, 0xFF, 0xFF, 0xFD, 0xB3, 0x0D, 
  /* RLE: 040 Pixels @ 004,004 */ 40, 0x00, 
  /* ABS: 007 Pixels @ 044,004 */ 0, 7, 0x0A, 0xB9, 0xFF, 0xFF, 0xFF, 0xED, 0x3A, 
  /* RLE: 042 Pixels @ 003,005 */ 42, 0x00, 
  /* ABS: 006 Pixels @ 045,005 */ 0, 6, 0x32, 0xF4, 0xFF, 0xFF, 0xAC, 0x04, 
  /* RLE: 042 Pixels @ 003,006 */ 42, 0x00, 
  /* ABS: 005 Pixels @ 045,006 */ 0, 5, 0x04, 0xAD, 0xFF, 0xFF, 0x6F, 
  /* RLE: 044 Pixels @ 002,007 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,007 */ 0, 4, 0x71, 0xFF, 0xFF, 0x4D, 
  /* RLE: 044 Pixels @ 002,008 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,008 */ 0, 4, 0x4E, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,009 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,009 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,010 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,010 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,011 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,011 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,012 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,012 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,013 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,013 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,014 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,014 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,015 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,015 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,016 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,016 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,017 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,017 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,018 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,018 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,019 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,019 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,020 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,020 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,021 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,021 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,022 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,022 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,023 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,023 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,024 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,024 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,025 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,025 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,026 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,026 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,027 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,027 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,028 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,028 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,029 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,029 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,030 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,030 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,031 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,031 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,032 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,032 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,033 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,033 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,034 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,034 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,035 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,035 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,036 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,036 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,037 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,037 */ 0, 4, 0x46, 0xFF, 0xFF, 0x46, 
  /* RLE: 044 Pixels @ 002,038 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,038 */ 0, 4, 0x46, 0xFF, 0xFF, 0x4E, 
  /* RLE: 044 Pixels @ 002,039 */ 44, 0x00, 
  /* ABS: 004 Pixels @ 046,039 */ 0, 4, 0x4E, 0xFF, 0xFF, 0x70, 
  /* RLE: 044 Pixels @ 002,040 */ 44, 0x00, 
  /* ABS: 005 Pixels @ 046,040 */ 0, 5, 0x6F, 0xFF, 0xFF, 0xAD, 0x04, 
  /* RLE: 042 Pixels @ 003,041 */ 42, 0x00, 
  /* ABS: 006 Pixels @ 045,041 */ 0, 6, 0x07, 0xAE, 0xFF, 0xFF, 0xF1, 0x35, 
  /* RLE: 042 Pixels @ 003,042 */ 42, 0x00, 
  /* ABS: 007 Pixels @ 045,042 */ 0, 7, 0x38, 0xED, 0xFF, 0xFF, 0xFF, 0xB9, 0x0A, 
  /* RLE: 040 Pixels @ 004,043 */ 40, 0x00, 
  /* ABS: 009 Pixels @ 044,043 */ 0, 9, 0x0D, 0xB3, 0xFD, 0xFF, 0xFF, 0xFF, 0xFD, 0x81, 0x0A, 
  /* RLE: 038 Pixels @ 005,044 */ 38, 0x00, 
  /* ABS: 003 Pixels @ 043,044 */ 0, 3, 0x0D, 0x85, 0xFB, 
  /* RLE: 005 Pixels @ 046,044 */ 5, 0xFF, 
  /* ABS: 004 Pixels @ 003,045 */ 0, 4, 0xFD, 0xBB, 0x36, 0x04, 
  /* RLE: 034 Pixels @ 007,045 */ 34, 0x00, 
  /* ABS: 004 Pixels @ 041,045 */ 0, 4, 0x07, 0x38, 0xB7, 0xFD, 
  /* RLE: 008 Pixels @ 045,045 */ 8, 0xFF, 
  /* ABS: 004 Pixels @ 005,046 */ 0, 4, 0xF4, 0xAD, 0x70, 0x4E, 
  /* RLE: 030 Pixels @ 009,046 */ 30, 0x46, 
  /* ABS: 005 Pixels @ 039,046 */ 0, 5, 0x4D, 0x6F, 0xAE, 0xED, 0xFD, 
  /* RLE: 052 Pixels @ 044,046 */ 52, 0xFF, 
  0
};  // 432 bytes for 2304 pixels

GUI_CONST_STORAGE GUI_BITMAP bmsettings_48_3 = {
  48, // xSize
  48, // ySize
  48, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acsettings_48_3,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
